theme: jekyll-theme-minimal

title: Antoine Jacquet
author :
  name : Antoine Jacquet
  email : antoine.jacquet@tse-fr.eu
  github : antoine-jacquet
logo: assets/images/bids.png
description: If economics is not for you, maybe you'll find interested in this cat picture.
show_downloads: false
google_analytics:

production_url : https://antoine-jacquet.github.io/
BASE_PATH : https://antoine-jacquet.github.io/
mathjax: true
