theme: jekyll-theme-minimal

title: Antoine Jacquet
author :
  name : Antoine Jacquet
  email : antoine.jacquet@tse-fr.eu
  github : antoine-jacquet
logo: assets/images/bids.png
description: If nothing else, maybe you'll be interested in this picture of my cat.
show_downloads: false
google_analytics:
website: https://www.tse-fr.eu/fr/people/antoine-jacquet

production_url : https://antoine-jacquet.github.io/
BASE_PATH : https://antoine-jacquet.github.io/
mathjax: true
