theme: jekyll-theme-minimal

title: Antoine Jacquet

author :
  name : Antoine Jacquet
  email : antoine.jacquet@tse-fr.eu
  github : antoine-jacquet

production_url : https://antoine-jacquet.github.io/
BASE_PATH : https://antoine-jacquet.github.io/

mathjax: true

<script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS_CHTML"></script>
