theme: jekyll-theme-minimal

# Setup
title: Antoine Jacquet
logo: assets/images/id_photo.jpg
description: Post-doctoral researcher <br> Sciences Po <br> Equiprice team
url: https://antoine-jacquet.github.io
email: mailto:antoine.jacquet@sciencespo.fr
website: https://www.tse-fr.eu/fr/people/antoine-jacquet

# Optimize Jekyll
exclude:
  - .gitignore
  - README.md

# Optimize Jekyll SEO Tag
#twitter:
#  username: vszhub
#  card: summary

# Others
BASE_PATH: https://antoine-jacquet.github.io/
show_downloads: false
google_analytics: G-YWFKS8377X
mathjax: true

# Specify the author for blog posts
author:
  name: Antoine Jacquet
  url: https://github.com/antoine-jacquet/
  email: antoine.jacquet@sciencespo.fr
  github: antoine-jacquet
