theme:

# Setup
title: Antoine Jacquet
logo: assets/images/bids.png
description:
url: https://antoine-jacquet.github.io
email: mailto:antoine.jacquet@tse-fr.eu
website: https://www.tse-fr.eu/fr/people/antoine-jacquet

# Optimize Jekyll
exclude:
  - .gitignore
  - README.md

# Optimize Jekyll SEO Tag
#twitter:
#  username: vszhub
#  card: summary

# Others
BASE_PATH: https://antoine-jacquet.github.io/
show_downloads: false
google_analytics:
mathjax: true

# Specify the author for blog posts
author:
  name: Antoine Jacquet
  url: https://github.com/antoine-jacquet/
  email: antoine.jacquet@tse-fr.eu
  github: antoine-jacquet
