theme: jekyll-theme-minimal

# Setup
title: Antoine Jacquet
logo: assets/images/bids.png
description: Here is a test description.
url: https://antoine-jacquet.github.io
social:
email: antoine.jacquet@tse-fr.eu
website: https://www.tse-fr.eu/fr/people/antoine-jacquet
twitter: https://www.tse-fr.eu/fr/people/antoine-jacquet

# Optimize Jekyll
exclude:
  - README.md

# Optimize Jekyll SEO Tag
#twitter:
#  username: vszhub
#  card: summary

# Others
BASE_PATH: https://antoine-jacquet.github.io/
show_downloads: false
google_analytics:
mathjax: true

# Specify the author for blog posts
author:
  name: Antoine Jacquet
  url: https://github.com/antoine-jacquet/
  email: antoine.jacquet@tse-fr.eu
  github: antoine-jacquet
